name: Mon_1er_Test

# On indique à Github quand le déclencher :
# Est ce qu'on le declenche au :
# push
# Pull request
# merge
# push sur la branch untel
on: push

# On declare des processus de travail
jobs: 
  # On donne un nom à notre job
  Tests: 
    runs-on: ubuntu-latest
    # On declare les taches que notre processus va executer
    steps:
      - name: "faire des tests"
        run: echo "Je fais des tests"
