name: WorkFlow_Push

on: push 

jobs: 
  # On donne un nom à notre job
  Tests: 
    runs-on: ubuntu-latest
    # On declare les taches que notre processus va executer
    steps:
      - name: je fais des tests
        run: echo "Je fais des tests"
 




